In [13]:
import torch

t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [14]:
n_samples = t_u.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices  

(tensor([1, 8, 7, 3, 6, 9, 2, 4, 5]), tensor([ 0, 10]))

In [15]:
train_t_u = t_u[train_indices]
train_t_c = t_c[train_indices]

val_t_u = t_u[val_indices]
val_t_c = t_c[val_indices]
train_t_un = 0.1 * train_t_u
val_t_un = 0.1 * val_t_u

val_t_un.shape

torch.Size([2])

In [20]:
import torch.nn as nn

linear_model = nn.Linear(2,1)
linear_model(val_t_un)

tensor([2.3077], grad_fn=<ViewBackward0>)

In [21]:
linear_model.weight

Parameter containing:
tensor([[-0.4637,  0.6579]], requires_grad=True)

In [22]:
linear_model.bias

Parameter containing:
tensor([-0.5366], requires_grad=True)

In [24]:
x = torch.ones(2)
linear_model(x)

tensor([-0.3425], grad_fn=<ViewBackward0>)

In [26]:
x = torch.ones(10, 1)
linear_model(x)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (10x1 and 2x1)